- name: install docker apt key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: docker apt repo
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
- name: install docker deps
  become: true
  apt:
    state: present
    name: ["docker-ce", "docker-ce-cli", "containerd.io", "docker-compose"]
