- name: web apt packages
  become: true
  apt:
    name: ["nginx", "certbot", "python3-certbot-nginx"]
- name: disable default site
  become: true
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx
- name: nginx config
  become: true
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 644
  notify: restart nginx
- name: lactobasilisk site
  become: true
  template:
    src: lactobasilisk.conf.j2
    dest: /etc/nginx/sites-enabled/lactobasilisk.conf
    mode: 644
  notify: restart nginx